# Site settings
email: hmzh.khn@gmail.com
baseurl: "khanh.github.io"
paginate: 5
paginate_path: "/blog/page-:num"
google_analytics: 

# SEO settings
title: Trophy
description: 
url: ""
twitter_username: 
default_img: 

# Profile settings
name: Hamzah Khan
profile_img: 
profile: 
social:
  github: khanh111

# Build settings
include: ["_categories"]
exclude: ["_screenshots", "Gemfile", "Gemfile.lock"]
markdown: kramdown
permalink: /:year/:month/:day/:title/

# Sass
sass:
  style: compressed

# Gems
gems: [jekyll-paginate, jekyll-sitemap, octopress-autoprefixer]
