# Site settings
email: hmzh.khn@gmail.com
baseurl: ""
paginate: 5
paginate_path: "/blog/page-:num"
google_analytics: UA-53666618-1

# SEO settings
title: Hamzah Khan
description: Muslim American, JS Developer, Harvey Mudd Student, and more
url: "Hamzah Khan's website"
twitter_username: hamzahikhan
default_img: 

# Profile settings
name: Hamzah Khan
profile_img: /assets/img/Self_Photo.jpg
profile: 
social:
  github: https://github.com/khanh111
  twitter: twitter.com/hamzahikhan
  stackoverflow: users/1701791/h-khan

# Build settings
include: ["_categories"]
exclude: ["_screenshots", "Gemfile", "Gemfile.lock"]
markdown: kramdown
permalink: /:year/:month/:day/:title/

# Sass
sass:
  sass_dir: _sass
  style: compressed

# Gems
gems: [jekyll-paginate, jekyll-sitemap, octopress-autoprefixer]
