# Site settings
email: hmzh.khn@gmail.com
baseurl: ""
paginate: 5
paginate_path: "/blog/page-:num"
google_analytics: G-SD92TQKKM0

# SEO settings
title: Hamzah Khan
description: Computer Scientist, Roboticist, Graduate Student at UT Austin, and more
url: "Hamzah Khan's website"
twitter_username: hamzahikhan
default_img: /assets/img/Self_Photo.jpg

# Profile settings
name: Hamzah Khan
profile_img: /assets/img/Self_Photo.jpg
profile: 
social:
  github: https://github.com/hmzh-khn
  linkedin: https://www.linkedin.com/in/hamzah-khan-02a02b59
  youtube: https://www.youtube.com/channel/UCGAGEYUAp22WBrDplYAn5Bw
  twitter: http://twitter.com/hamzahikhan
  instagram: https://instagram.com/hamzahs_view

# Build settings
include: ["_categories"]
exclude: ["_screenshots", "Gemfile", "Gemfile.lock", "vendor"]
markdown: kramdown
kramdown:
  math_engine: mathjax
permalink: /:year/:month/:day/:title/

# Sass
sass:
  sass_dir: _sass
  style: compressed

# Gems
plugins: [jekyll-paginate, jekyll-sitemap, kramdown-parser-gfm, octopress-autoprefixer]
